version: "2"


services:
 blockexchange_blue:
  image: blockexchange/blockexchange
  restart: always
  depends_on:
   - postgres
  env_file:
   - blockexchange.env
  labels:
   - "promtail=true"
  logging:
   options:
    max-size: 50m

 blockexchange_green:
  image: blockexchange/blockexchange
  restart: always
  depends_on:
   - postgres
  env_file:
   - blockexchange.env
  labels:
   - "promtail=true"
  logging:
   options:
    max-size: 50m

 redis:
  image: redis:7.2.3-alpine
  restart: always
  labels:
   - "promtail=true"

 postgres:
  image: postgres:16.1
  restart: always
  shm_size: '2gb'
  environment:
   POSTGRES_PASSWORD: enter
  labels:
   - "promtail=true"
  volumes:
   - "./data/postgres:/var/lib/postgresql/data"
  command:
   - "postgres"
   - "-c"
   - "shared_buffers=4GB"
   - "-c"
   - "synchronous_commit=off"
  logging:
   options:
    max-size: 50m

 haproxy:
  image: haproxy:2.9.1
  networks:
   - terminator
   - default
  restart: always
  depends_on:
   - blockexchange_blue
   - blockexchange_green
  labels:
    - "promtail=true"
    - "traefik.enable=true"
    - "traefik.docker.network=terminator"
    - "traefik.http.routers.blockexchange.rule=Host(`blockexchange.minetest.ch`)"
    - "traefik.http.services.blockexchange.loadbalancer.server.port=80"
    - "traefik.http.routers.blockexchange.entrypoints=websecure"
    - "traefik.http.routers.blockexchange.tls.certresolver=default"
  volumes:
   - "./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro"
  logging:
   options:
    max-size: 50m

networks:
 terminator:
  external: true
